# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 有个博客
email: airport.0930@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://afghl.github.io" # the base hostname & protocol for your site
github_username:  afghl

plugins:
  - jekyll-archives

# Build settings
highlighter: rouge
theme: minimal-mistakes-jekyll

include:
  - _pages

encoding: "utf-8"

author:
  name   : "小码农"
  avatar : "/images/avatar.jpg"
  email  : "airport.0930@gmail.com"
  uri    : "http://afghl.github.io"

paginate_path: /page:num/

tag_archive:
  type: liquid
  path: /tags/
paginate: 15


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      layout: single
      classes: wide
      share: true
      related: true
